version: '2.2'
services:
    php-apache:
        image: php:7.2.1-apache
        ports:
        - "8080:80"
        volumes:
            - ./DocumentRoot:/var/www/jangomart
        links:
        - wordpress_db:mysql
    wordpress_db:
        image: mariadb
        environment:
         MYSQL_USERNAME: root
         MYSQL_ROOT_PASSWORD: olawale
